on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm ci
      - run: npm test
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run get-data
      - run: npm run get-narratives
      - run: npm run smoke-test:ci
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
  # bundlesize:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - run: npm install
  #     - run: npx bundlesize
